import{A as P,S as b,K as q,M as k,N,a as M}from"./assets/vendor-f92b6250.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const x=document.querySelector(".accordeon-list");new P(x,{duration:600,showMultiple:!0,openOnInit:[0]});const I=document.querySelectorAll(".accordeon-title");I.forEach(e=>{e.addEventListener("click",function(){const t=e.querySelector(".title-icon"),r=e.nextElementSibling;t.classList.toggle("active-is"),r.classList.toggle("hidden")})});const O=document.querySelector(".swiper-next"),V=document.querySelector(".about-me-swiper-container"),p=new b(".about-me-skills",{modules:[q,k],speed:800,loop:!0,slidesPerView:2,slideActiveClass:"swiper-content-wrap-active",keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:{invert:!0},breakpoints:{375:{slidesPerView:2},768:{slidesPerView:3},1440:{slidesPerView:6}},slideToClickedSlide:!0});O.addEventListener("click",()=>{p.slideNext()});V.addEventListener("keydown",function(e){e.preventDefault(),e.key==="Tab"?p.slideNext():p.slidePrev()});document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".reviews-swiper-container"),t=document.querySelector(".swiper-button-prev"),r=document.querySelector(".swiper-button-next"),n=new b(e,{modules:[N],slidesPerView:4,spaceBetween:20,navigation:{nextEl:r,prevEl:t},keyboard:!0,breakpoints:{320:{slidesPerView:1},340:{slidesPerView:1},768:{slidesPerView:2},1024:{slidesPerView:4}}});o();async function o(){try{const i=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(!i.ok)throw new Error("Failed to fetch reviews");const l=await i.json();if(l.length===0){a();return}s(l)}catch(i){console.error("Error fetching reviews:",i),E("Failed to fetch reviews. Please try again later.")}}function s(i){const l=i.map(d=>`
        <div class="swiper-slide">
          <div class="review-card">
            <img src="${d.avatar_url}" alt="${d.author}'s avatar" class="review-avatar" />
            <div class="review-author">${d.author}</div>
            <div class="review-text">${d.review}</div>
          </div>
        </div>
      `).join("");e.querySelector(".swiper-wrapper").innerHTML=l,n.update(),g()}function a(){e.querySelector(".swiper-wrapper").innerHTML='<p class="not-found">No content available</p>',n.destroy()}function E(i){alert(i)}function g(){n.isBeginning?t.classList.add("swiper-button-disabled"):t.classList.remove("swiper-button-disabled"),n.isEnd?r.classList.add("swiper-button-disabled"):r.classList.remove("swiper-button-disabled")}n.on("slideChange",g)});function T(e){try{const t=localStorage.getItem(e);return t===null?void 0:JSON.parse(t)}catch(t){console.error("Load state error: ",t);return}}function f(e,t){try{const r=JSON.stringify(t);localStorage.setItem(e,r)}catch(r){console.error("Save state error: ",r)}}const w=document.querySelector(".footer-form"),L=document.getElementById("user-email"),S=document.getElementById("user-comment"),y=document.querySelector(".backdrop"),C=document.querySelector(".modal"),A=document.querySelector(".close-btn"),B=document.querySelector(".modal-title"),F=document.querySelector(".modal-message");w.addEventListener("submit",async function(e){e.preventDefault();const t=L.value,r=S.value;if(!t||!r){u("Error!","Please fill in both fields");return}const n={email:t,comment:r};f("email",t),f("comment",r);try{const s=(await M.post("https://portfolio-js.b.goit.study/api/requests",n,{headers:{"Content-Type":"application/json"}})).data;s.error?u("Error!",`${s.error}`):(localStorage.removeItem(h),w.reset(),u("Thank you for your interest in cooperation!","The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch."))}catch(o){u("Error!",`Request failed with status code ${o.response.status}`)}});function u(e,t){B.textContent=e,F.textContent=t,$()}function $(){y.classList.add("is-open"),document.body.classList.contains("scroll-off")||document.body.classList.add("scroll-off")}function v(){y.classList.remove("is-open"),document.body.classList.contains("scroll-off")&&document.body.classList.remove("scroll-off")}A.addEventListener("click",v);document.addEventListener("keydown",e=>{e.key==="Escape"&&y.classList.contains("is-open")&&v()});document.addEventListener("click",e=>{e.composedPath().includes(C)||v()});const h="feedback-form-state",m=T(h),c={email:"",comments:""};m&&(c.email=m.email,c.comments=m.comments);L.value=c.email;S.value=c.comments;w.addEventListener("input",e=>{c[e.target.name]=e.target.value.trim(),f(h,c)});
//# sourceMappingURL=commonHelpers.js.map
